version: '2'
services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    ports:
      - ${ZOOKEEPER_PORT}:2181
  kafka:
    image: ${KAFKA_IMAGE}
    links:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      ZOOKEEPER_IP: ${HOST_IP}
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
  cassandra:
    image: ${CASSANDRA_IMAGE}