version: '2'
services:
  kafka:
    image: ${KAFKA_IMAGE}
    ports:
      - ${KAFKA_PORT}:9092
      - ${ZOOKEEPER_PORT}:2181
    environment:
      ADVERTISED_PORT: ${KAFKA_PORT}
      ADVERTISED_HOST: ${HOST_IP}
      ZOOKEEPER_IP: ${HOST_IP}
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
  postgres:
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}:5432
